config:
  watchPlugins: true
image:
  registry: "ghcr.io"
  repository: "headlamp-k8s/headlamp"
  tag: "latest"
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    external-dns.alpha.kubernetes.io/hostname: headlamp.mb.scalefactory.net
  labels:
    environment: demo
  ingressClassName: alb
  hosts:
    - host: headlamp.mb.scalefactory.net
      paths:
        - path: /
          type: Prefix
  #tls:
  #  - hosts:
  #      - headlamp.mb.scalefactory.net
pluginsManager:
  enabled: true
  configContent: |
    plugins:
      - name: kompose
        source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_kompose
        version: 0.1.0-beta-1
      #- name: karpenter
      #  source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_karpenter
      #  version: 0.1.0
      - name: logo
        source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_example_change_logo
        version: 0.0.1-1
      - name: ai
        source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_ai_assistant
        version: 0.1.0-alpha
      - name: external-secrets
        source: https://artifacthub.io/packages/headlamp/external-secrets-operator-headlamp-plugin/external-secrets-operator
        version: 0.1.0-beta7
      #- name: catalog
      #  source: https://artifacthub.io/packages/headlamp/test-123/appcatalog_headlamp_plugin
      #  version: 0.0.3
      - name: kubescape
        source: https://artifacthub.io/packages/headlamp/kubescape-headlamp-plugin/headlamp_kubescape
        version: 0.10.3
    installOptions:
      parallel: true
      maxConcurrent: 2
  baseImage: node:lts-alpine
  version: latest
